select * from user_tables;
desc member;
select * from user_constraints;

SELECT * FROM MEMBER;

SELECT ID, PWD FROM MEMBER WHERE ID='PARK' AND PWD='123';
SELECT ID, PWD, PHOTO, POINT FROM MEMBER;
UPDATE MEMBER SET PWD='111', PHOTO='TEMPPATH' WHERE ID='AN';

--ID        NOT NULL VARCHAR2(20)  
--PWD       NOT NULL VARCHAR2(20)  
--PHOTO     NOT NULL VARCHAR2(200) 
--MEM_ADMIN NOT NULL NUMBER        
--POINT     NOT NULL NUMBER   

INSERT INTO MEMBER VALUES ('CHOI', '123', 'PATH', 1, DEFAULT);
INSERT INTO MEMBER VALUES ('PARK', '123', 'PATH', 0, DEFAULT);
INSERT INTO MEMBER VALUES ('KIM', '123', 'PATH', 0, DEFAULT);
INSERT INTO MEMBER VALUES ('JO', '123', 'PATH', 0, DEFAULT);
INSERT INTO MEMBER VALUES ('SON', '123', 'PATH', 0, DEFAULT);
INSERT INTO MEMBER VALUES ('AN', '123', 'PATH', 0, DEFAULT);
INSERT INTO MEMBER VALUES ('SEOL', '123', 'PATH', 0, DEFAULT);
INSERT INTO MEMBER VALUES ('JI', '123', 'PATH', 0, DEFAULT);
INSERT INTO MEMBER VALUES ('KI', '123', 'PATH', 0, DEFAULT);
INSERT INTO MEMBER VALUES ('choi', '123', 'PATH', 1, DEFAULT);
INSERT INTO MEMBER VALUES ('park', '123', 'PATH', 0, DEFAULT);
INSERT INTO MEMBER VALUES ('kim', '123', 'PATH', 0, DEFAULT);
INSERT INTO MEMBER VALUES ('jo', '123', 'PATH', 0, DEFAULT);
INSERT INTO MEMBER VALUES ('son', '123', 'PATH', 0, DEFAULT);
INSERT INTO MEMBER VALUES ('an', '123', 'PATH', 0, DEFAULT);
INSERT INTO MEMBER VALUES ('seol', '123', 'PATH', 0, DEFAULT);
INSERT INTO MEMBER VALUES ('ji', '123', 'PATH', 0, DEFAULT);
INSERT INTO MEMBER VALUES ('ki', '123', 'PATH', 0, DEFAULT);

SELECT ID, PWD, PHOTO, POINT FROM MEMBER;

commit;

SELECT COUNT(*) c FROM MEMBER WHERE ID='CHOI';
select * from member;
select * from member;
commit;
select * from user_tables;
desc notice;
--BOARD_NO       NOT NULL NUMBER         
--NOTICE_TYPE    NOT NULL NUMBER(1)   
--NOTICE_CONTENT          VARCHAR2(1000) 
--BOARD_DATE     NOT NULL TIMESTAMP(6)   
--BOARD_READ_NO  NOT NULL NUMBER     
ALTER TABLE NOTICE MODIFY (NOTICE_TYPE NUMBER(1));
ALTER TABLE NOTICE MODIFY (NOTICE_TYPE NUMBER(1) DEFAULT 2);
INSERT INTO NOTICE VALUES (1, 'SUBJECT', NULL, SYSTIMESTAMP, DEFAULT, 2, 'ORIGINNAME', 'FILEPATH');
INSERT INTO NOTICE VALUES (2, 'SUBJECT', NULL, SYSTIMESTAMP, DEFAULT, 1, 'ORIGINNAME', 'FILEPATH');
INSERT INTO NOTICE VALUES (13, 'SUBJECT', NULL, SYSTIMESTAMP, DEFAULT, 1, 'ORIGINNAME', 'FILEPATH');
INSERT INTO NOTICE VALUES (14, 'SUBJECT', NULL, SYSTIMESTAMP, DEFAULT, 1, 'ORIGINNAME', 'FILEPATH');
INSERT INTO NOTICE VALUES (15, 'SUBJECT', NULL, SYSTIMESTAMP, DEFAULT, 1, 'ORIGINNAME', 'FILEPATH');
INSERT INTO NOTICE VALUES (16, 'SUBJECT', NULL, SYSTIMESTAMP, DEFAULT, 1, 'ORIGINNAME', 'FILEPATH');
INSERT INTO NOTICE VALUES (17, 'SUBJECT', NULL, SYSTIMESTAMP, DEFAULT, 2, 'ORIGINNAME', 'FILEPATH');
INSERT INTO NOTICE VALUES (8, 'SUBJECT', NULL, SYSTIMESTAMP, DEFAULT, 2, 'ORIGINNAME', 'FILEPATH');
INSERT INTO NOTICE VALUES (9, 'SUBJECT', NULL, SYSTIMESTAMP, DEFAULT, 2, 'ORIGINNAME', 'FILEPATH');
INSERT INTO NOTICE VALUES (10, 'SUBJECT', NULL, SYSTIMESTAMP, DEFAULT, 2, 'ORIGINNAME', 'FILEPATH');
INSERT INTO NOTICE VALUES (11, 'SUBJECT', NULL, SYSTIMESTAMP, DEFAULT, 2, 'ORIGINNAME', 'FILEPATH');
INSERT INTO NOTICE VALUES (12, 'SUBJECT', NULL, SYSTIMESTAMP, DEFAULT, 2, 'ORIGINNAME', 'FILEPATH');
COMMIT;
desc notice;
alter table notice rename column board_no to NOTICE_NO;
COMMIT;
DESC NOTICE;
ALTER TABLE NOTICE ADD (NOTICE_SUBJECT VARCHAR2(100));
ALTER TABLE NOTICE MODIFY (NOTICE_SUBJECT NOT NULL);
SELECT * FROM NOTICE;
UPDATE NOTICE SET NOTICE_SUBJECT = 'SUBJECT';
CREATE OR REPLACE PROCEDURE NOTICE_INSERT ( 
    P_WRITER_KEY BOARD.BOARD_WRITER%TYPE, P_SUBJECT_STR BOARD.SUBJECT%TYPE, P_MAXCOUNT NUMBER)
IS
    T_N BOARD%ROWTYPE;
BEGIN
    FOR I IN 1..P_MAXCOUNT LOOP
            SELECT SEQ_BOARD_ID.NEXTVAL INTO V_B.BOARD_ID FROM DUAL;
            V_B.BOARD_WRITER := P_WRITER_KEY;
            INSERT INTO BOARD
            VALUES
            (   V_B.BOARD_ID,
                P_SUBJECT_STR||I,
                '내용----'||I,
                DEFAULT,
                '127.0.0.1',
                V_B.BOARD_WRITER,
                DEFAULT
            );
    END LOOP;
END;
/
exec NOTICE_INSERT('kh2', '제목', 100);

CREATE TABLE "FILE" (
	"FILE_ORIGIN_NAME"	VARCHAR(255)		NOT NULL,
	"FILE_SAVE_PATH"	VARCHAR(255)		NOT NULL,
	"BOARD_PROB_NO"	NUMBER		NULL,
	"BOARD_ASK_NO"	NUMBER		NULL,
	"BOARD_ANY_NO"	NUMBER		NULL,
	"BOARD_NO"	NUMBER		NULL
);
COMMENT ON COLUMN "FILE"."FILE_ORIGIN_NAME" IS '파일실제이름';

COMMENT ON COLUMN "FILE"."FILE_SAVE_PATH" IS '파일저장이름';

COMMENT ON COLUMN "FILE"."BOARD_PROB_NO" IS '문제게시판번호';

COMMENT ON COLUMN "FILE"."BOARD_ASK_NO" IS '문의게시판번호';

COMMENT ON COLUMN "FILE"."BOARD_ANY_NO" IS '자유게시판번호';

COMMENT ON COLUMN "FILE"."BOARD_NO" IS '공지 번호';

ALTER TABLE "FILE" ADD CONSTRAINT "FK_BOARD_PROBLEM_TO_FILE_1" FOREIGN KEY (
	"BOARD_PROB_NO"
)
REFERENCES "BOARD_PROBLEM" (
	"BOARD_PROB_NO"
);
ALTER TABLE "FILE" ADD CONSTRAINT "FK_ASK_TO_FILE_1" FOREIGN KEY (
	"BOARD_ASK_NO"
)
REFERENCES "ASK" (
	"BOARD_ASK_NO"
);

ALTER TABLE "FILE" ADD CONSTRAINT "FK_BOARD_ANY_TO_FILE_1" FOREIGN KEY (
	"BOARD_ANY_NO"
)
REFERENCES "BOARD_ANY" (
	"BOARD_ANY_NO"
);

ALTER TABLE "FILE" ADD CONSTRAINT "FK_NOTICE_TO_FILE_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "NOTICE" (
	"BOARD_NO"
);

COMMIT;

DESC FILE;

select * from user_tables;
drop table BOARD_PROBLEM;
select * from BOARD_PROBLEM;

commit;
select * from notice;
desc file;

SELECT SEQ_BOARD_ID.nextval FROM DUAL;
SELECT SEQ_BOARD_ID.currval FROM DUAL;
select * from user_tables;
select * from user_tables;
desc notice;
DESC NOTICE;
SELECT NOTICE_NO, FILE_ORIGIN_NAME, FILE_SAVE_PATH FROM NOTICE WHERE NOTICE_NO=?;
SELECT * FROM NOTICE;
SELECT COUNT(*) CNT FROM NOTICE;
SELECT t2.* 
    FROM (SELECT T1.*, ROWNUM RN
    FROM (SELECT NOTICE_NO, NOTICE_SUBJECT, NOTICE_CONTENT, BOARD_DATE, BOARD_READ_NO, NOTICE_TYPE, FILE_ORIGIN_NAME, FILE_SAVE_PATH FROM NOTICE ORDER BY NOTICE_NO DESC) T1 ) T2
    WHERE RN BETWEEN 4   and 8;
SELECT NOTICE_NO, NOTICE_SUBJECT, NOTICE_CONTENT, BOARD_DATE, BOARD_READ_NO FROM NOTICE;
desc notice;
commit;
SELECT NOTICE_NO, NOTICE_SUBJECT, NOTICE_CONTENT, BOARD_DATE, BOARD_READ_NO, NOTICE_TYPE FROM NOTICE WHERE NOTICE_NO=1;
CREATE SEQUENCE SEQ_NOTICE_NO;
SELECT SEQ_NOTICE_NO.NEXTVAL FROM DUAL;
ALTER SEQUENCE SEQ_NOTICE_NO NOCYCLE;
DROP SEQUENCE SEQ_NOTICE_NO;
COMMIT;

UPDATE NOTICE SET BOARD_READ_NO=BOARD_READ_NO+1 WHERE NOTICE_NO=1;
select * from notice;

select * from user_tables;
commit;

select * from notice;
select * from member;
insert into member values ('aa', 'aa', 'path', default, default);


