select * from user_tables;
desc member;
select * from user_constraints;

SELECT * FROM MEMBER;

SELECT ID, PWD FROM MEMBER WHERE ID='PARK' AND PWD='123';
SELECT ID, PWD, PHOTO, POINT FROM MEMBER;
UPDATE MEMBER SET PWD='111', PHOTO='TEMPPATH' WHERE ID='AN';

--ID        NOT NULL VARCHAR2(20)  
--PWD       NOT NULL VARCHAR2(20)  
--PHOTO     NOT NULL VARCHAR2(200) 
--MEM_ADMIN NOT NULL NUMBER        
--POINT     NOT NULL NUMBER   

INSERT INTO MEMBER VALUES ('CHOI', '123', 'PATH', 1, DEFAULT);
INSERT INTO MEMBER VALUES ('PARK', '123', 'PATH', 0, DEFAULT);
INSERT INTO MEMBER VALUES ('KIM', '123', 'PATH', 0, DEFAULT);
INSERT INTO MEMBER VALUES ('JO', '123', 'PATH', 0, DEFAULT);
INSERT INTO MEMBER VALUES ('SON', '123', 'PATH', 0, DEFAULT);
INSERT INTO MEMBER VALUES ('AN', '123', 'PATH', 0, DEFAULT);
INSERT INTO MEMBER VALUES ('SEOL', '123', 'PATH', 0, DEFAULT);
INSERT INTO MEMBER VALUES ('JI', '123', 'PATH', 0, DEFAULT);
INSERT INTO MEMBER VALUES ('KI', '123', 'PATH', 0, DEFAULT);

SELECT ID, PWD, PHOTO, POINT FROM MEMBER;

commit;
