
SELECT COUNT(*) CNT FROM LOST;
SELECT T2.*
	FROM (SELECT T1.*, ROWNUM RN
		FROM (SELECT BOARD_NO, LOST_SUBJECT, BOARD_DATE, FILE_SAVE_PATH FROM LOST ORDER BY BOARD_NO DESC) T1 ) T2
		WHERE RN BETWEEN 7 and 15;
desc lost;
SELECT ROWNUM, LOST_SUBJECT, BOARD_DATE, FILE_SAVE_PATH
    FROM (SELECT LOST_SUBJECT, BOARD_DATE, FILE_SAVE_PATH FROM LOST ORDER BY BOARD_NO DESC);
commit;

SELECT * FROM USER_TABLES;
SELECT * FROM PRICE;
DESC PRICE;
--PRICE_TYPE NOT NULL NUMBER   / 0 - 1일권, 1 - 5회권, 2 - 10회권, 3 - 1개월, 4 - 3개월     
--PRICE      NOT NULL NUMBER        / 20,000, 90,000, 170,000, 130,000, 330,000
--PRICE_DESC          VARCHAR2(100)  / 5회권 이용기간 3개월, 10 회권 이용기간 6개월, 1개월 및 3개월 권 15일 정지 가능
--SERVICE_ON NOT NULL CHAR(1) DEFAULT 1 / 0 - 서비스 종료, 1 - 서비스 중
INSERT INTO PRICE VALUES (0, 20000, '일일 자유이용권', 1);
INSERT INTO PRICE VALUES (1, 90000, '5회권', 1);
INSERT INTO PRICE VALUES (2, 170000, '10회권', 1);
INSERT INTO PRICE VALUES (3, 130000, '1개월 이용권', 1);
INSERT INTO PRICE VALUES (4, 330000, '3개월 이용권', 1);
SELECT * FROM PRICE;
COMMIT;
ALTER TABLE PRICE MODIFY (PRICE_DESC VARCHAR2(200));

ALTER TABLE LOST MODIFY (BOARD_DATE DATE DEFAULT SYSDATE);

SELECT * FROM RENT;
DESC RENT;
--RENT_ITEM   NOT NULL NUMBER       
--SHOE_SIZE            NUMBER       
--SHOE_COUNT           NUMBER       
--CHALK_COUNT          NUMBER       
--PAY_DATE    NOT NULL TIMESTAMP(6) DEFAULT SYSTIMESTAMP FK

select * from user_tables;
select * from member;
SELECT * FROM PHOTO;
desc member;
ALTER TABLE MEMBER MODIFY (POINT NULL);
DESC PHOTO;
INSERT ALL
    INTO MEMBER (ID, PWD, EMAIL) 
        VALUES (?, ?, ?)
    INTO PHOTO (ID, PHOTO_NAME, PHOTO_SAVE_PATH)
        VALUES (?, ?, ?)
    SELECT * FROM DUAL;
        
INSERT ALL
    INTO MEMBER (ID, PWD, EMAIL, POINT, MEM_ADMIN) 
        VALUES ('abc', '123', 'eamil', DEFAULT, DEFAULT)
    INTO PHOTO (ID, PHOTO_NAME, PHOTO_SAVE_PATH)
        VALUES ('abc', 'photo', 'path')
    SELECT * FROM DUAL;
    
commit;
select * from member;
select * from photo;
SELECT COUNT(*) c FROM MEMBER WHERE ID=lower('CHOI');
SELECT ID, PWD, MEM_ADMIN, POINT, EMAIL FROM MEMBER WHERE ID='choi';
select * from member;
desc member;
select * from notice;
desc notice;
ALTER TABLE NOTICE DROP (FILE_SAVE_PATH);
ALTER TABLE NOTICE DROP (FILE_ORIGIN_NAME);
ALTER TABLE NOTICE MODIFY (NOTICE_CONTENT VARCHAR2(2000));
COMMIT;
SELECT * FROM NOTICE;
DESC NOTICE;
--NOTICE_NO      NOT NULL NUMBER         
--NOTICE_SUBJECT NOT NULL VARCHAR2(100)  
--NOTICE_CONTENT          VARCHAR2(2000) 
--BOARD_DATE     NOT NULL TIMESTAMP(6)   
--BOARD_READ_NO  NOT NULL NUMBER         
--NOTICE_TYPE    NOT NULL NUMBER   
SELECT ROWNUM, NOTICE_NO, NOTICE_SUBJECT, NOTICE_CONTENT, BOARD_DATE, BOARD_READ_NO, NOTICE_TYPE
    FROM (SELECT NOTICE_NO, NOTICE_SUBJECT, NOTICE_CONTENT, BOARD_DATE, BOARD_READ_NO, NOTICE_TYPE FROM NOTICE ORDER BY NOTICE_NO DESC);
SELECT * FROM USER_SEQUENCES;
INSERT ALL
    INTO NOTICE (NOTICE_NO, NOTICE_SUBJECT, NOTICE_CONTENT, BOARD_DATE, BOARD_READ_NO, NOTICE_TYPE)
        VALUES (SEQ_NOTICE_NO.NEXTVAL, 'SUBJECT', 'CONTENT', SYSTIMESTAMP, DEFAULT, DEFAULT)
    INTO NOTICE_FILE (NOTICE_NO, FILE_NAME, FILE_SAVE_PATH)
        VALUES (SEQ_NOTICE_NO.NEXTVAL, 'FILENAME', 'FILESAVEPATH')
    SELECT * FROM DUAL;
        
ALTER TABLE NOTICE_FILE MODIFY ( FILE_SAVE_PATH VARCHAR2(200));
select * from notice;
select * from notice_file;
commit;
SELECT T2.*
	FROM (SELECT T1.*, ROWNUM RN
		FROM (SELECT NOTICE_NO, NOTICE_SUBJECT, BOARD_DATE, BOARD_READ_NO, NOTICE_TYPE FROM NOTICE ORDER BY NOTICE_TYPE ASC, NOTICE_NO DESC) T1 ) T2
		 WHERE RN BETWEEN 1 and 100;
SELECT * FROM NOTICE;
select * from member;
ALTER TABLE NOTICE DROP (FILE_SAVE_PATH);

select * from notice_file;
SELECT NOTICE_NO, NOTICE_SUBJECT, NOTICE_CONTENT, BOARD_DATE, BOARD_READ_NO, NOTICE_TYPE FROM NOTICE WHERE NOTICE_NO=9;

select * from user_tables;
select * from reply;
desc reply;
select * from notice;
UPDATE NOTICE SET NOTICE_CONTENT='TESTESTESTESTESTESTESTESTESTESTESTESTESTSETSETSETSETSETSETSETSETSET' WHERE NOTICE_NO=4;
COMMIT;
select * from notice;
alter session set nls_date_format='yy/mm/dd hh24:mi:ss';
select sysdate from dual;
select systimestamp from dual;
select * from notice;
select * from notice_file;
SELECT NOTICE_NO, FILE_NAME, FILE_SAVE_PATH FROM NOTICE WHERE NOTICE_NO=26;
DELETE FROM NOTICE_FILE WHERE NOTICE_NO = 26;
SELECT * FROM NOTICE_FILE;
DESC NOTICE_FILE;
SELECT NOTICE_NO, FILE_SAVE_PATH, FILE_ORIGIN_NAME FROM NOTICE_FILE;
SELECT NOTICE_NO, FILE_SAVE_PATH, FILE_ORIGIN_NAME FROM NOTICE_FILE;

