--멤버
DESC MEMBER;
--ID        NOT NULL VARCHAR2(20)  
--PWD       NOT NULL VARCHAR2(20)  
--PHOTO     NOT NULL VARCHAR2(200) 
--MEM_ADMIN NOT NULL NUMBER        
--POINT     NOT NULL NUMBER 
INSERT INTO MEMBER VALUES ('ID_D', 'PWD', 'PHOTO', 0, 10000);

--가격
DESC PRICE;
--PRICE_TYPE NOT NULL NUMBER        
--PRICE      NOT NULL NUMBER        
--PRICE_DESC          VARCHAR2(100) 
--SERVICE_ON NOT NULL CHAR(1)  
INSERT INTO PRICE VALUES (4, 1000, 'PRICE_DESC',0);

--구매내역
DESC PAY_HISTORY;
--PAY_DATE    NOT NULL TIMESTAMP(6) 
--USE_HISTORY          NUMBER       
--END_DATE             DATE         
--ID          NOT NULL VARCHAR2(20) 
--PRICE_TYPE  NOT NULL NUMBER  
alter session set nls_date_format='yyyy-mm-dd hh24:mi:ss';
INSERT INTO PAY_HISTORY VALUES (SYSTIMESTAMP, 1, SYSDATE, 'ID_D', 1);
SELECT * FROM PAY_HISTORY;

--회원 
DESC MEMBERSHIP;
--MEM_HISTORY            TIMESTAMP(6) 
--MEM_LOCKER_NO          NUMBER       
--MEM_LOCKER    NOT NULL CHAR(1)      
--PAY_DATE      NOT NULL TIMESTAMP(6) 
INSERT INTO MEMBERSHIP VALUES (SYSTIMESTAMP, 3, DEFAULT, '24/04/10 11:00:47.063000000');

--대여
DESC RENT;
--RENT_ITEM   NOT NULL NUMBER       
--SHOE_SIZE            NUMBER       
--SHOE_COUNT           NUMBER       
--CHALK_COUNT          NUMBER       
--PAY_DATE    NOT NULL TIMESTAMP(6) 
INSERT INTO RENT VALUES (1, NULL, NULL, NULL, '24/04/10 11:00:41.054000000');
INSERT INTO RENT VALUES (1, NULL, NULL, NULL, '24/04/10 11:00:45.290000000');
INSERT INTO RENT VALUES (1, NULL, NULL, NULL, '24/04/10 11:00:47.063000000');
INSERT INTO RENT VALUES (1, NULL, NULL, NULL, '24/04/10 11:00:49.009000000');

--문제게시판
DESC BOARD_PROBLEM;
--BOARD_PROB_NO      NOT NULL NUMBER        
--PROB_SECTOR                 NUMBER        
--PROB_LEVEL                  NUMBER        
--PROB_VIDEO                  VARCHAR2(200) 
--PROB_CONTENT                VARCHAR2(200) 
--BOARD_PROB_DATE    NOT NULL DATE          
--BOARD_PROB_READ_NO NOT NULL NUMBER        
--ID                 NOT NULL VARCHAR2(20) 
INSERT INTO BOARD_PROBLEM VALUES (1, NULL, NULL, NULL, NULL, DEFAULT, DEFAULT, 'ID_A');
INSERT INTO BOARD_PROBLEM VALUES (2, NULL, NULL, NULL, NULL, DEFAULT, DEFAULT, 'ID_B');
INSERT INTO BOARD_PROBLEM VALUES (3, NULL, NULL, NULL, NULL, DEFAULT, DEFAULT, 'ID_C');
INSERT INTO BOARD_PROBLEM VALUES (4, NULL, NULL, NULL, NULL, DEFAULT, DEFAULT, 'ID_D');
SELECT * FROM MEMBER;

--문의
DESC ASK;
--BOARD_ASK_NO      NOT NULL NUMBER         
--ASK_CONTENT       NOT NULL VARCHAR2(1000) 
--BOARD_ASK_DATE    NOT NULL DATE           
--ASK_ANSWER                 VARCHAR2(100)  
--BOARD_ASK_READ_NO NOT NULL NUMBER         
--ASK_PWN_YN        NOT NULL CHAR(1)        
--ASK_PWD                    VARCHAR2(20)   
--ID                NOT NULL VARCHAR2(20)  
INSERT INTO ASK VALUES (1, 'A', SYSDATE, NULL, DEFAULT, DEFAULT, NULL, 'ID_A');
INSERT INTO ASK VALUES (2, 'A', SYSDATE, NULL, DEFAULT, DEFAULT, NULL, 'ID_B');
INSERT INTO ASK VALUES (3, 'A', SYSDATE, NULL, DEFAULT, DEFAULT, NULL, 'ID_C');
INSERT INTO ASK VALUES (4, 'A', SYSDATE, NULL, DEFAULT, DEFAULT, NULL, 'ID_D');

--자유게시판
DESC BOARD_ANY;
--BOARD_ANY_NO      NOT NULL NUMBER         
--ANY_CONTENT                VARCHAR2(1000) 
--BOARD_ANY_DATE    NOT NULL DATE           
--BOARD_ANY_READ_NO          NUMBER         
--ID                NOT NULL VARCHAR2(20)   
INSERT INTO BOARD_ANY VALUES (1, NULL, DEFAULT, DEFAULT, 'ID_A');
INSERT INTO BOARD_ANY VALUES (2, NULL, DEFAULT, DEFAULT, 'ID_B');
INSERT INTO BOARD_ANY VALUES (3, NULL, DEFAULT, DEFAULT, 'ID_C');
INSERT INTO BOARD_ANY VALUES (4, NULL, DEFAULT, DEFAULT, 'ID_D');

-- 댓글
DESC REPLY;
--BOARD_REPLY_ID    NOT NULL NUMBER       
--BOARD_REPLY_LEVEL NOT NULL NUMBER(2)    
--BOARD_REPLY_REF   NOT NULL NUMBER       
--BOARD_REPLY_STEP  NOT NULL NUMBER(3)    
--ID                NOT NULL VARCHAR2(20) 
--BOARD_ANY_NO               NUMBER       
--BOARD_ASK_NO               NUMBER       
--BOARD_PROB_NO              NUMBER  
INSERT INTO REPLY VALUES (1, DEFAULT, 0, DEFAULT, 'ID_A', NULL, NULL, NULL);
INSERT INTO REPLY VALUES (2, DEFAULT, 0, DEFAULT, 'ID_B', NULL, NULL, NULL);
INSERT INTO REPLY VALUES (3, DEFAULT, 0, DEFAULT, 'ID_C', NULL, NULL, NULL);
INSERT INTO REPLY VALUES (4, DEFAULT, 0, DEFAULT, 'ID_D', NULL, NULL, NULL);
ALTER TABLE REPLY MODIFY BOARD_ANY_NO NULL;
ALTER TABLE REPLY MODIFY BOARD_ASK_NO NULL;
ALTER TABLE REPLY MODIFY BOARD_PROB_NO NULL;

--강습
DESC LESSON;
--LESSON_CODE  NOT NULL NUMBER       
--LESSON_TYPE  NOT NULL CHAR(1)      
--LESSON_LEVEL NOT NULL NUMBER       
--LESSON_START NOT NULL DATE         
--LESSON_END   NOT NULL DATE         
--TEACHER_NO   NOT NULL NUMBER       
--LESSON_TIME  NOT NULL NUMBER       
--LESSON_DAY   NOT NULL VARCHAR2(10) 
INSERT INTO LESSON VALUES (1, '1', 1, DEFAULT, SYSDATE, 0, 0, '요일');
INSERT INTO LESSON VALUES (2, 2, 1, DEFAULT, SYSDATE, 0, 0, '요일');
INSERT INTO LESSON VALUES (3, 3, 1, DEFAULT, SYSDATE, 0, 0, '요일');
INSERT INTO LESSON VALUES (4, 4, 1, DEFAULT, SYSDATE, 0, 0, '요일');
INSERT INTO LESSON VALUES (5, 5, 1, DEFAULT, SYSDATE, 0, 0, '요일');

-회원_강습
DESC MEM_LESSON;
--ID          NOT NULL VARCHAR2(20) 
--LESSON_CODE NOT NULL NUMBER  
INSERT INTO MEM_LESSON VALUES ('ID_A', 1);
INSERT INTO MEM_LESSON VALUES ('ID_A', 2);
INSERT INTO MEM_LESSON VALUES ('ID_A', 3);
INSERT INTO MEM_LESSON VALUES ('ID_A', 4);
SELECT * FROM MEM_LESSON;

--공지
DESC NOTICE;
--BOARD_NO       NOT NULL NUMBER         
--NOTICE_CONTENT          VARCHAR2(1000) 
--BOARD_DATE     NOT NULL TIMESTAMP(6)   
--BOARD_READ_NO  NOT NULL NUMBER   
--NOTICE_TYPE    NOT NULL NUMBER
INSERT INTO NOTICE VALUES (1, NULL, SYSTIMESTAMP, 0, 0);
INSERT INTO NOTICE VALUES (2, NULL, SYSTIMESTAMP, 0, 0);
INSERT INTO NOTICE VALUES (3, NULL, SYSTIMESTAMP, 0, 0);
INSERT INTO NOTICE VALUES (4, NULL, SYSTIMESTAMP, 0, 0);
ALTER TABLE NOTICE DROP COLUMN NOTICE_TYPE;
ALTER TABLE NOTICE ADD (NOTICE_TYPE NUMBER);
SELECT * FROM NOTICE;
DESC NOTICE;

--운영시간
DESC OPENTIME;
--OPEN_TIME       VARCHAR2(20) 
--CLOSE_DATE      DATE         
--CLOSE_REASON    VARCHAR2(40) 
INSERT INTO OPENTIME VALUES (NULL, NULL, NULL);

--분실물
DESC LOST;
--BOARD_NO   NOT NULL NUMBER       
--LOST_TYPE  NOT NULL VARCHAR2(20) 
--LOST_PLACE          VARCHAR2(20) 
--LOST_TIME           TIMESTAMP(6) 
--BOARD_DATE NOT NULL DATE   
INSERT INTO LOST VALUES (1, '기타', NULL, NULL, DEFAULT);
INSERT INTO LOST VALUES (2, '기타', NULL, NULL, DEFAULT);
INSERT INTO LOST VALUES (3, '기타', NULL, NULL, DEFAULT);
INSERT INTO LOST VALUES (4, '기타', NULL, NULL, DEFAULT);
SELECT * FROM LOST;

SELECT * FROM USER_TABLES;
SELECT * FROM MEMBER;
SELECT * FROM LESSON;
SELECT * FROM OPENTIME;
SELECT * FROM BOARD_PROBLEM;
SELECT * FROM BOARD_ANY;
SELECT * FROM ASK;
SELECT * FROM NOTICE;
SELECT * FROM LOST;
SELECT * FROM RENT;
SELECT * FROM MEMBERSHIP;
SELECT * FROM PRICE;
SELECT * FROM PAY_HISTORY;
SELECT * FROM MEM_LESSON;
SELECT * FROM REPLY;


