
SELECT COUNT(*) CNT FROM LOST;
SELECT T2.*
	FROM (SELECT T1.*, ROWNUM RN
		FROM (SELECT BOARD_NO, LOST_SUBJECT, BOARD_DATE, FILE_SAVE_PATH FROM LOST ORDER BY BOARD_NO DESC) T1 ) T2
		WHERE RN BETWEEN 7 and 15;
desc lost;
SELECT ROWNUM, LOST_SUBJECT, BOARD_DATE, FILE_SAVE_PATH
    FROM (SELECT LOST_SUBJECT, BOARD_DATE, FILE_SAVE_PATH FROM LOST ORDER BY BOARD_NO DESC);
SELECT * FROM USER_TABLES;
SELECT * FROM PRICE;
DESC PRICE;
--PRICE_TYPE NOT NULL NUMBER   / 0 - 1일권, 1 - 5회권, 2 - 10회권, 3 - 1개월, 4 - 3개월     
--PRICE      NOT NULL NUMBER        / 20,000, 90,000, 170,000, 130,000, 330,000
--PRICE_DESC          VARCHAR2(100)  / 5회권 이용기간 3개월, 10 회권 이용기간 6개월, 1개월 및 3개월 권 15일 정지 가능
--SERVICE_ON NOT NULL CHAR(1) DEFAULT 1 / 0 - 서비스 종료, 1 - 서비스 중
INSERT INTO PRICE VALUES (0, 20000, '일일 자유이용권', 1);
INSERT INTO PRICE VALUES (1, 90000, '5회권', 1);
INSERT INTO PRICE VALUES (2, 170000, '10회권', 1);
INSERT INTO PRICE VALUES (3, 130000, '1개월 이용권', 1);
INSERT INTO PRICE VALUES (4, 330000, '3개월 이용권', 1);
SELECT * FROM PRICE;
COMMIT;
ALTER TABLE PRICE MODIFY (PRICE_DESC VARCHAR2(200));

ALTER TABLE LOST MODIFY (BOARD_DATE DATE DEFAULT SYSDATE);

SELECT * FROM RENT;
DESC RENT;
--RENT_ITEM   NOT NULL NUMBER       
--SHOE_SIZE            NUMBER       
--SHOE_COUNT           NUMBER       
--CHALK_COUNT          NUMBER       
--PAY_DATE    NOT NULL TIMESTAMP(6) DEFAULT SYSTIMESTAMP FK

select * from user_tables;
select * from member;
SELECT * FROM PHOTO;
desc member;
ALTER TABLE MEMBER MODIFY (POINT NULL);
DESC PHOTO;
INSERT ALL
    INTO MEMBER (ID, PWD, EMAIL) 
        VALUES (?, ?, ?)
    INTO PHOTO (ID, PHOTO_NAME, PHOTO_SAVE_PATH)
        VALUES (?, ?, ?)
    SELECT * FROM DUAL;
        
INSERT ALL
    INTO MEMBER (ID, PWD, EMAIL, POINT, MEM_ADMIN) 
        VALUES ('abc', '123', 'eamil', DEFAULT, DEFAULT)
    INTO PHOTO (ID, PHOTO_NAME, PHOTO_SAVE_PATH)
        VALUES ('abc', 'photo', 'path')
    SELECT * FROM DUAL;
    
commit;
select * from member;
select * from photo;
SELECT COUNT(*) c FROM MEMBER WHERE ID=lower('CHOI');
SELECT ID, PWD, MEM_ADMIN, POINT, EMAIL FROM MEMBER WHERE ID='choi';
select * from member;
desc member;
select * from notice;
desc notice;
ALTER TABLE NOTICE DROP (FILE_SAVE_PATH);
ALTER TABLE NOTICE DROP (FILE_ORIGIN_NAME);
ALTER TABLE NOTICE MODIFY (NOTICE_CONTENT VARCHAR2(2000));
COMMIT;
SELECT * FROM NOTICE;
DESC NOTICE;
--NOTICE_NO      NOT NULL NUMBER         
--NOTICE_SUBJECT NOT NULL VARCHAR2(100)  
--NOTICE_CONTENT          VARCHAR2(2000) 
--BOARD_DATE     NOT NULL TIMESTAMP(6)   
--BOARD_READ_NO  NOT NULL NUMBER         
--NOTICE_TYPE    NOT NULL NUMBER   
SELECT ROWNUM, NOTICE_NO, NOTICE_SUBJECT, NOTICE_CONTENT, BOARD_DATE, BOARD_READ_NO, NOTICE_TYPE
    FROM (SELECT NOTICE_NO, NOTICE_SUBJECT, NOTICE_CONTENT, BOARD_DATE, BOARD_READ_NO, NOTICE_TYPE FROM NOTICE ORDER BY NOTICE_NO DESC);
SELECT * FROM USER_SEQUENCES;
INSERT ALL
    INTO NOTICE (NOTICE_NO, NOTICE_SUBJECT, NOTICE_CONTENT, BOARD_DATE, BOARD_READ_NO, NOTICE_TYPE)
        VALUES (SEQ_NOTICE_NO.NEXTVAL, 'SUBJECT', 'CONTENT', SYSTIMESTAMP, DEFAULT, DEFAULT)
    INTO NOTICE_FILE (NOTICE_NO, FILE_NAME, FILE_SAVE_PATH)
        VALUES (SEQ_NOTICE_NO.NEXTVAL, 'FILENAME', 'FILESAVEPATH')
    SELECT * FROM DUAL;
        
ALTER TABLE NOTICE_FILE MODIFY ( FILE_SAVE_PATH VARCHAR2(200));
select * from notice;
select * from notice_file;
commit;
SELECT T2.*
	FROM (SELECT T1.*, ROWNUM RN
		FROM (SELECT NOTICE_NO, NOTICE_SUBJECT, BOARD_DATE, BOARD_READ_NO, NOTICE_TYPE FROM NOTICE ORDER BY NOTICE_TYPE ASC, NOTICE_NO DESC) T1 ) T2
		 WHERE RN BETWEEN 1 and 100;
SELECT * FROM NOTICE;
select * from member;
ALTER TABLE NOTICE DROP (FILE_SAVE_PATH);

select * from notice_file;
SELECT NOTICE_NO, NOTICE_SUBJECT, NOTICE_CONTENT, BOARD_DATE, BOARD_READ_NO, NOTICE_TYPE FROM NOTICE WHERE NOTICE_NO=9;

select * from user_tables;
select * from reply;
desc reply;
select * from notice;
UPDATE NOTICE SET NOTICE_CONTENT='TESTESTESTESTESTESTESTESTESTESTESTESTESTSETSETSETSETSETSETSETSETSET' WHERE NOTICE_NO=4;
COMMIT;
select * from notice;
alter session set nls_date_format='yy/mm/dd hh24:mi:ss';
select sysdate from dual;
select systimestamp from dual;
select * from notice;
select * from notice_file;
SELECT NOTICE_NO, FILE_NAME, FILE_SAVE_PATH FROM NOTICE WHERE NOTICE_NO=26;
DELETE FROM NOTICE_FILE WHERE NOTICE_NO = 26;
SELECT * FROM NOTICE_FILE;
DESC NOTICE_FILE;
SELECT NOTICE_NO, FILE_SAVE_PATH, FILE_ORIGIN_NAME FROM NOTICE_FILE;
SELECT NOTICE_NO, FILE_SAVE_PATH, FILE_ORIGIN_NAME FROM NOTICE_FILE;
select * from lesson;
desc lesson;
ALTER TABLE LESSON MODIFY ( LESSON_CAPACITY NUMBER);
DELETE FROM LESSON LESSON_CAPACITY;
--LESSON_CODE     NOT NULL NUMBER       
--LESSON_TYPE     NOT NULL CHAR(1)      
--LESSON_LEVEL             NUMBER       
--LESSON_START             DATE         
--LESSON_END               DATE         
--TEACHER_NAME             VARCHAR2(20) 
--LESSON_TIME              NUMBER       
--LESSON_DAY               VARCHAR2(40) 
--LESSON_DURATION          NUMBER       
--LESSON_CAPACITY          NUMBER  
SELECT LESSON_CODE, LESSON_TYPE, LESSON_LEVEL, LESSON_START, LESSON_END, TEACHER_NAME, LESSON_TIME, LESSON_DAY, LESSON_DURATION, LESSON_CAPACITY FROM LESSON;
commit;
SELECT LESSON_TIME, LESSON_DAY, LESSON_CAPACITY
	FROM (SELECT * FROM LESSON WHERE LESSON_TYPE = 0 ORDER BY LESSON_TIME);
UPDATE LESSON SET LESSON_CAPACITY=0 WHERE LESSON_CAPACITY IN NULL;
ALTER TABLE LESSON MODIFY (LESSON_CAPACITY NUMBER DEFAULT 0);
SELECT * FROM LESSON;
SELECT * FROM MEMBER;
SELECT * FROM MEM_LESSON;
DESC MEM_LESSON;
INSERT INTO MEM_LESSON (ID, LESSON_CODE)
    VALUES ('choi', 100);
DELETE FROM MEM_LESSON WHERE ID='choi';

SELECT LESSON_CODE, LESSON_LEVEL, LESSON_START, LESSON_END, TEACHER_NAME, LESSON_TIME,
	LESSON_DAY, LESSON_DURATION, LESSON_CAPACITY
	FROM LESSON WHERE LESSON_TYPE=1 AND LESSON_DAY IN ('월,수,금', '화,목') ORDER BY LESSON_CODE;
    
    
    
select * from user_tables;
select * from member;
select * from lesson;
select * from notice;
desc lesson;
select * from board_problem;
DESC BOARD_PROBLEM;
TRUNCATE TABLE BOARD_PROBLEM;
ALTER TABLE BOARD_PROBLEM DROP (VIDEO_SAVE_PATH);
INSERT 
    INTO BOARD_PROBLEM (BOARD_PROB_NO, PROB_SUBJECT, PROB_SECTOR, PROB_LEVEL, PROB_CONTENT, BOARD_PROB_DATE, BOARD_PROB_READ_NO, MEMBER_ID, BOARD_TYPE )
        VALUES (SEQ_BOARD_PROBLEM.NEXTVAL, 'SUBJECT', 'SECTOR', 1, 'CONTENT', DEFAULT, DEFAULT, 'choi', 0);
DESC ;
INSERT ALL
    INTO BOARD_PROBLEM (BOARD_PROB_NO, PROB_SUBJECT, PROB_SECTOR, PROB_LEVEL, PROB_CONTENT, BOARD_PROB_DATE, BOARD_PROB_READ_NO, MEMBER_ID, BOARD_TYPE )
        VALUES (SEQ_BOARD_PROBLEM.NEXTVAL, 'SUBJECT', 'SECTOR', 1, 'CONTENT', DEFAULT, DEFAULT, 'choi', 0)
    INTO BOARD_PROB_VIDEO (BOARD_PROB_NO, VIDEO_SAVE_PATH, VIDEO_NAME)
        VALUES (SEQ_BOARD_PROBLEM.NEXTVAL, 'SAVE_PATH', 'NAME')
    SELECT * FROM DUAL;
DESC BOARD_PROB_VIDEO;
DESC BOARD_PROB_VIDEO;
SELECT * FROM BOARD_PROB_VIDEO;
SELECT SEQ_BOARD_PROBLEM.NEXTVAL FROM DUAL;
select * from board_problem;
desc board_problem;

SELECT T2.*
	FROM (SELECT T1.*, ROWNUM RN
		FROM (SELECT BOARD_PROB_NO, PROB_SUBJECT, PROB_SECTOR, PROB_LEVEL, BOARD_PROB_DATE, MEMBER_ID, BOARD_PROB_READ_NO, BOARD_TYPE FROM BOARD_PROBLEM ORDER BY BOARD_PROB_NO DESC) T1 ) T2
		WHERE RN BETWEEN 1 and 5;
DESC BOARD_PROBLEM;
ALTER TABLE BOARD_PROBLEM DROP (PROM_SUBJECT);
SELECT T2.*
	FROM (SELECT T1.*, ROWNUM RN
		FROM (SELECT BOARD_PROB_NO, PROB_SUBJECT, PROB_SECTOR, PROB_LEVEL, BOARD_PROB_DATE, MEMBER_ID, BOARD_PROB_READ_NO, BOARD_TYPE FROM BOARD_PROBLEM ORDER BY BOARD_PROB_NO DESC) T1 ) T2
		WHERE RN BETWEEN 5 and 10;
select * from user_tables;
desc board_prob_video;
COMMIT;

SELECT * FROM NOTICE_FILE;
DESC NOTICE_FILE;
desc board_problem;
--	private Integer boardProbNo;
--	private String probSubject;
--	private String probSector;
--	private Integer probLevel;
--	private String probContent;
--	private String boardProbDate;
--	private Integer boardProbReadNo;
--	private String memberId;
--	private Integer boardType;
--BOARD_PROB_NO      NOT NULL NUMBER        
--BOARD_TYPE         NOT NULL NUMBER        
--PROB_SECTOR                 VARCHAR2(20)  
--PROB_LEVEL                  NUMBER        
--PROB_CONTENT                VARCHAR2(400) 
--BOARD_PROB_DATE    NOT NULL TIMESTAMP(6)  
--BOARD_PROB_READ_NO NOT NULL NUMBER        
--PROB_SUBJECT       NOT NULL VARCHAR2(100) 
--MEMBER_ID          NOT NULL VARCHAR2(20)  
SELECT BOARD_PROB_NO, PROB_SUBJECT, PROB_SECTOR, PROB_LEVEL, PROB_CONTENT, BOARD_PROB_DATE, BOARD_PROB_READ_NO, MEMBER_ID, BOARD_TYPE FROM BOARD_PROBLEM;

select * from board_prob_video;
SELECT BOARD_PROB_NO, VIDEO_SAVE_PATH, VIDEO_NAME FROM BOARD_PROB_VIDEO WHERE BOARD_PROB_NO=38;

select * from MEM_LESSON;
DESC MEM_LESSON;
INSERT INTO MEM_LESSON (ID, LESSON_CODE)
    VALUES (?, ?);
INSERT INTO MEM_LESSON (ID, LESSON_CODE)
    VALUES ('choi', 500);
SELECT * FROM MEM_LESSON;
SELECT * FROM LESSON;
TRUNCATE TABLE MEM_LESSON;
SELECT * FROM NOTICE;
UPDATE NOTICE SET BOARD_READ_NO=BOARD_READ_NO+1 WHERE NOTICE_NO=1;
commit;

SELECT * FROM USER_TABLES;
DESC MEMBERSHIP;
SELECT * FROM MEMBERSHIP;
SELECT * FROM PRICE;
DESC PRICE;
SELECT * FROM PAY_HISTORY;
DESC PAY_HISTORY;
INSERT INTO PAY_HISTORY VALUES (DEFAULT, NULL, NULL, 'choi', 0);
--PAY_DATE    NOT NULL SYSDATE
--USE_HISTORY          NUMBER       
--END_DATE             DATE         
--ID          NOT NULL VARCHAR2(20) 
--PRICE_TYPE  NOT NULL NUMBER  

desc membership;
--MEM_HISTORY            TIMESTAMP(6) 
--MEM_LOCKER_NO          NUMBER       
--MEM_LOCKER    NOT NULL CHAR(1)      
--PAY_DATE      NOT NULL DATE 
SELECT * FROM PAY_HISTORY;
TRUNCATE TABLE PAY_HISTORY;
INSERT INTO MEMBERSHIP VALUES (DEFAULT, 66, 'Y', TO_DATE('24/04/26', 'YY/MM/DD'));
ALTER TABLE MEMBERSHIP MODIFY (MEM_HISTORY DATE DEFAULT SYSDATE);
COMMIT;

INSERT ALL
    INTO PAY_HISTORY VALUES (SYSDATE, NULL, NULL, 'choi', 0)
    INTO MEMBERSHIP VALUES (DEFAULT, 66, 'Y', SYSDATE)
    SELECT * FROM DUAL;

DESC MEM_LESSON;
SELECT * FROM USER_TABLES;
INSERT INTO MEM_LESSON VALUES ('choi', 100);
TRUNCATE TABLE MEM_LESSON;
select * from mem_lesson;

DESC LESSON;
ALTER TABLE LESSON MODIFY (LESSON_CAPACITY NUMBER DEFAULT 0);
UPDATE LESSON SET LESSON_CAPACITY = NULL;
select * from lesson;

commit;
select * from mem_lesson;
ALTER TABLE MEM_LESSON DROP (LESSON_CAPACITY);
select * from lesson where (LESSON_CODE > 99);
desc lesson;
UPDATE LESSON SET LESSON_CAPACITY = LESSON_CAPACITY+1 WHERE (LESSON_CODE = 100);
UPDATE LESSON SET LESSON_CAPACITY = 0 WHERE LESSON_CODE=100;
COMMIT;

select * from user_tables;

--REPLY
--CLOSE_DAY
--OPENTIME
--RENT
--MEMBERSHIP
desc membership;
SELECT * FROM MEMBERSHIP;


--TODO
select * from member;
desc member;
--ID        NOT NULL VARCHAR2(20) 
--PWD       NOT NULL VARCHAR2(20) 
--MEM_ADMIN NOT NULL NUMBER       
--POINT     NOT NULL NUMBER       
--EMAIL     NOT NULL VARCHAR2(30) 
--choi	123	1	0	A@A.COM
--kyung	123	0	0	A@A.COM 
desc price;
--PRICE_TYPE NOT NULL NUMBER        
--PRICE      NOT NULL NUMBER        
--PRICE_DESC          VARCHAR2(200) 
--SERVICE_ON NOT NULL CHAR(1)
--0	20000	일일 자유이용권	1
--1	90000	5회권	1
--2	170000	10회권	1
--3	130000	1개월 이용권	1
--4	330000	3개월 이용권	1
desc pay_history;
--PAY_DATE    NOT NULL TIMESTAMP(6) 
--USE_HISTORY          NUMBER       
--END_DATE             DATE         
--ID          NOT NULL VARCHAR2(20) 
--PRICE_TYPE  NOT NULL NUMBER     
desc membership;
--MEM_HISTORY            TIMESTAMP(6) 
--MEM_LOCKER_NO          NUMBER       
--MEM_LOCKER    NOT NULL CHAR(1)      
--PAY_DATE      NOT NULL TIMESTAMP(6)
INSERT INTO PAY_HISTORY;

