
SELECT COUNT(*) CNT FROM LOST;
SELECT T2.*
	FROM (SELECT T1.*, ROWNUM RN
		FROM (SELECT BOARD_NO, LOST_SUBJECT, BOARD_DATE, FILE_SAVE_PATH FROM LOST ORDER BY BOARD_NO DESC) T1 ) T2
		WHERE RN BETWEEN 7 and 15;
desc lost;
SELECT ROWNUM, LOST_SUBJECT, BOARD_DATE, FILE_SAVE_PATH
    FROM (SELECT LOST_SUBJECT, BOARD_DATE, FILE_SAVE_PATH FROM LOST ORDER BY BOARD_NO DESC);
commit;

SELECT * FROM USER_TABLES;
SELECT * FROM PRICE;
DESC PRICE;
--PRICE_TYPE NOT NULL NUMBER   / 0 - 1일권, 1 - 5회권, 2 - 10회권, 3 - 1개월, 4 - 3개월     
--PRICE      NOT NULL NUMBER        / 20,000, 90,000, 170,000, 130,000, 330,000
--PRICE_DESC          VARCHAR2(100)  / 5회권 이용기간 3개월, 10 회권 이용기간 6개월, 1개월 및 3개월 권 15일 정지 가능
--SERVICE_ON NOT NULL CHAR(1) DEFAULT 1 / 0 - 서비스 종료, 1 - 서비스 중
INSERT INTO PRICE VALUES (0, 20000, '일일 자유이용권', 1);
INSERT INTO PRICE VALUES (1, 90000, '5회권', 1);
INSERT INTO PRICE VALUES (2, 170000, '10회권', 1);
INSERT INTO PRICE VALUES (3, 130000, '1개월 이용권', 1);
INSERT INTO PRICE VALUES (4, 330000, '3개월 이용권', 1);
SELECT * FROM PRICE;
COMMIT;
ALTER TABLE PRICE MODIFY (PRICE_DESC VARCHAR2(200));

ALTER TABLE LOST MODIFY (BOARD_DATE DATE DEFAULT SYSDATE);

SELECT * FROM RENT;
DESC RENT;
--RENT_ITEM   NOT NULL NUMBER       
--SHOE_SIZE            NUMBER       
--SHOE_COUNT           NUMBER       
--CHALK_COUNT          NUMBER       
--PAY_DATE    NOT NULL TIMESTAMP(6) DEFAULT SYSTIMESTAMP FK

select * from user_tables;


